language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - testing-ruby
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - i@nukshuk.io
    on_success: change
    on_failure: always
